spring:
  application:
    name: mall-search
  profiles:
    active: dev #기본값은 개발 환경입니다
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8081

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml



